# Generated by Django 4.2.3 on 2023-07-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('price', models.CharField(blank=True, default='Not Specified', max_length=15)),
                ('pages', models.CharField(blank=True, default='Not Specified', max_length=15)),
                ('ratings', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
