# Generated by Django 4.2.3 on 2023-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
